// Generated by LiveScript 1.4.0
(function(){
  var express, app;
  express = require('express');
  app = express();
  if (process.env.PORT == null) {
    process.env.PORT = 8080;
  }
  app.listen(process.env.PORT, '0.0.0.0');
  app.get('/', function(req, res){
    return res.send('hello world');
  });
}).call(this);
