// Generated by LiveScript 1.4.0
(function(){
  var express, path, app;
  express = require('express');
  path = require('path');
  app = express();
  if (process.env.PORT == null) {
    process.env.PORT = 8080;
  }
  app.listen(process.env.PORT, '0.0.0.0');
  app.get('/', function(req, res){
    return res.send('hello world');
  });
  app.use(express['static'](path.join(__dirname, 'public')));
}).call(this);
